#!/usr/bin/env python3
"""
Wrapper to run Robot Framework tests with runtime sandbox credentials.

Writes Resources/TestData/EnvData.robot (overriding URL/username/password), then
executes robot with standard output.xml, log.html, and report.html under Results/.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from datetime import datetime
from pathlib import Path


ROOT = Path(__file__).resolve().parent
ENVDATA_PATH = ROOT / "Resources" / "TestData" / "EnvData.robot"


def escape_robot_scalar(value: str) -> str:
    """Escape characters that would break Robot variable parsing."""
    return value.replace("\\", "\\\\").replace("$", "\\$")


def write_envdata(sandbox_url: str, username: str, password: str) -> None:
    sandbox_url = sandbox_url.strip()
    if not sandbox_url.endswith("/"):
        sandbox_url += "/"

    u = escape_robot_scalar(username)
    p = escape_robot_scalar(password)
    url = escape_robot_scalar(sandbox_url)

    content = f"""*** Variables ***
# Generated by run_test.py — do not edit by hand for CI; use the runner or edit and run robot directly.
${{globalSandboxTestUrl}}=    {url}
${{sandboxUserNameInput}}=    {u}
${{sandboxPasswordInput}}=    {p}
"""
    ENVDATA_PATH.parent.mkdir(parents=True, exist_ok=True)
    ENVDATA_PATH.write_text(content, encoding="utf-8")


def build_robot_run(
    sandbox_url: str,
    username: str,
    password: str,
    test_path: str | Path,
    results_root: str = "Results",
    run_name: str | None = None,
    robot_args: list[str] | None = None,
    *,
    headless: bool = False,
) -> tuple[list[str], Path]:
    """
    Write EnvData and return the robot command (argv list) and output directory.

    When headless is True, passes ``-v headless:true`` so ``Begin Web Test`` opens
    Chrome with ``--headless=new``. When False, no headless variable is passed and
    the browser runs visibly (PM / debug).
    """
    write_envdata(sandbox_url, username, password)

    test_target = Path(test_path)
    if not test_target.is_absolute():
        test_target = ROOT / test_target
    if not test_target.exists():
        raise FileNotFoundError(f"Test path does not exist: {test_target}")

    resolved_run_name = run_name or f"run_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
    out_dir = ROOT / results_root / resolved_run_name
    out_dir.mkdir(parents=True, exist_ok=True)

    extra = list(robot_args or [])
    if extra and extra[0] == "--":
        extra = extra[1:]

    robot_cli = shutil.which("robot")
    if robot_cli:
        cmd_prefix = [robot_cli]
    else:
        cmd_prefix = [sys.executable, "-m", "robot"]

    cmd = [
        *cmd_prefix,
        "--outputdir",
        str(out_dir),
        "--output",
        "output.xml",
        "--log",
        "log.html",
        "--report",
        "report.html",
    ]
    if headless:
        cmd.extend(["-v", "headless:true"])
    else:
        # Visible browser: allow Login To Sandbox to pause for manual MFA/OTP after password step.
        cmd.extend(["-v", "MFA_PAUSE_FOR_MANUAL_COMPLETION:true"])
    cmd.append(str(test_target))
    cmd.extend(extra)
    return cmd, out_dir


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Run Robot Framework tests with dynamic EnvData credentials.",
    )
    p.add_argument(
        "--sandbox_url",
        required=True,
        help="Salesforce sandbox login URL (e.g. https://myorg--sandbox.sandbox.my.salesforce.com/)",
    )
    p.add_argument("--username", required=True, help="Sandbox username")
    p.add_argument("--password", required=True, help="Sandbox password")
    p.add_argument(
        "--test_path",
        required=True,
        help="Path to a .robot suite or directory (relative to project root or absolute)",
    )
    p.add_argument(
        "--results-root",
        default="Results",
        help="Directory under project root for run output (default: Results)",
    )
    p.add_argument(
        "--run-name",
        default=None,
        help="Subfolder name under results-root (default: run_YYYYMMDD_HHMMSS)",
    )
    p.add_argument(
        "--headless",
        action="store_true",
        help="Run Chrome headless via -v headless:true (Background mode).",
    )
    p.add_argument(
        "robot_args",
        nargs=argparse.REMAINDER,
        help="Extra args passed to robot after '--' e.g. -- --tag smoke",
    )
    return p.parse_args()


def main() -> int:
    args = parse_args()
    try:
        cmd, out_dir = build_robot_run(
            args.sandbox_url,
            args.username,
            args.password,
            args.test_path,
            results_root=args.results_root,
            run_name=args.run_name,
            robot_args=args.robot_args,
            headless=args.headless,
        )
    except FileNotFoundError as e:
        print(f"Error: {e}", file=sys.stderr)
        return 2

    print("Working directory:", ROOT)
    print("Output directory:", out_dir)
    print("Command:", " ".join(cmd))
    completed = subprocess.run(cmd, cwd=ROOT)
    return int(completed.returncode)


if __name__ == "__main__":
    sys.exit(main())
